

export const userConstants = {
    USERLOGIN_REQUEST: "USERLOGIN_REQUEST",
    USERLOGIN_SUCCESS: "USERLOGIN_SUCCESS",
    USERLOGIN_FAIL: "USERLOGIN_FAIL",

    BLOGLIST_REQUEST: "BLOGLIST_REQUEST",
    BLOGLIST_SUCCESS: "BLOGLIST_SUCCESS",
    BLOGLIST_FAIL: "BLOGLIST_FAIL",

    BLOGADD_REQUEST: "BLOGADD_REQUEST",
    BLOGADD_SUCCESS: "BLOGADD_SUCCESS",
    BLOGLADD_FAIL: "BLOGLADD_FAIL",

}